name: Real-time Log Shipper
on:
  workflow_run:
    workflows: ["CI Worker"]
    types:
      - requested

permissions:
  actions: read

jobs:
  log-shipper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Stream logs to HTTP server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          # gh run watch "$RUN_ID" | curl -X POST -d @- http://your-log-server.com
          gh run watch "$RUN_ID"
