name: Real-time Log Shipper
on:
  workflow_run:
    workflows: ["CI Worker"]
    types:
      - requested

permissions:
  actions: read

jobs:
  log-shipper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Build Job ID
        id: get_job_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          # Find the specific ID for the 'build' job within the triggering workflow run.
          BUILD_JOB_ID=$(gh run view $RUN_ID --json jobs -q '.jobs[] | select(.name == "build") | .id')
          echo "build_job_id=$BUILD_JOB_ID" >> $GITHUB_OUTPUT

      - name: Stream Logs to HTTP Server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_JOB_ID: ${{ steps.get_job_id.outputs.build_job_id }}
        run: |
          echo "Found build job ID: $BUILD_JOB_ID"
          echo "Starting to poll for logs..."

          # Poll for logs every 15 seconds while the job is in progress.
          while gh run view $BUILD_JOB_ID --json status -q '.status' | grep -q 'in_progress'; do
            echo "Job is in progress. Fetching latest logs..."
            gh run view $BUILD_JOB_ID --log | curl -X POST -H "X-GitHub-Job-ID: $BUILD_JOB_ID" -d @- http://your-log-server.com
            sleep 15
          done

          # The job is finished. Send the final, complete log one last time.
          echo "Job has finished. Sending final complete log..."
          gh run view $BUILD_JOB_ID --log | curl -X POST -H "X-GitHub-Job-ID: $BUILD_JOB_ID" -d @- http://your-log-server.com
          echo "Log shipping complete."
