name: Real-time Log Shipper
on:
  workflow_run:
    workflows: ["CI Worker"]
    types:
      - requested

permissions:
  actions: read

jobs:
  log-shipper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Build Job ID
        id: get_job_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          # Find the specific ID for the 'build' job within the triggering workflow run.
          # This assumes your CI Worker has a job named 'build'.
          BUILD_JOB_ID=$(gh run view $RUN_ID --json jobs -q '.jobs[] | select(.name == "build") | .id')
          echo "build_job_id=$BUILD_JOB_ID" >> $GITHUB_OUTPUT

      - name: Stream Logs to HTTP Server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_JOB_ID: ${{ steps.get_job_id.outputs.build_job_id }}
          LOG_SECRET: ${{ secrets.LOG_SECRET }}
        run: |
          echo "Found build job ID: $BUILD_JOB_ID"
          echo "Starting to poll for logs..."

          # Poll for logs every 15 seconds while the job is in progress.
          # The `gh` CLI is pre-installed on GitHub-hosted runners.
          while gh run view $BUILD_JOB_ID --json status -q '.status' | grep -q 'in_progress'; do
            echo "Job is in progress. Fetching latest logs..."
            LOG_CONTENT=$(gh run view $BUILD_JOB_ID --log)
            # SIGNATURE=$(echo -n "$LOG_CONTENT" | openssl dgst -sha256 -hmac "$LOG_SECRET" | sed 's/^.* //')
            echo "--- Log Content Update ---"
            echo "$LOG_CONTENT"
            # curl -X POST \
            #      -H "X-GitHub-Job-ID: $BUILD_JOB_ID" \
            #      -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
            #      -d "$LOG_CONTENT" \
            #      http://your-log-server.com/logs
            sleep 15 # Adjust this value to control polling frequency and API usage.
          done

          # The job is finished. Send the final, complete log one last time.
          echo "Job has finished. Sending final complete log..."
          LOG_CONTENT=$(gh run view $BUILD_JOB_ID --log)
          # SIGNATURE=$(echo -n "$LOG_CONTENT" | openssl dgst -sha256 -hmac "$LOG_SECRET" | sed 's/^.* //')
          echo "--- Final Log Content ---"
          echo "$LOG_CONTENT"
          # curl -X POST \
          #      -H "X-GitHub-Job-ID: $BUILD_JOB_ID" \
          #      -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
          #      -d "$LOG_CONTENT" \
          #      http://your-log-server.com/logs
          echo "Log shipping complete."
