name: Real-time Log Shipper
on:
  push:
    branches:
      - main
jobs:
  log-shipper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debugging Info
        run: |
          echo "hello"
          ls -al
          pwd

      - name: Stream logs to HTTP server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
        run: |
          # This is a proof-of-concept and may have limitations.
          # For a more robust solution, consider using a dedicated logging service or a more advanced script.
          # We are using a simple approach of tailing the logs of the current run using `gh` and piping them to `curl`.
          # This might not capture all logs in real-time, especially for very short-lived jobs.

          # Install GitHub CLI
          sudo apt-get update
          sudo apt-get install -y gh

          # Watch the logs of the current run, print them to the job's output, and send them to the server
          # Replace http://your-log-server.com with your actual log server URL
          gh run watch "$RUN_ID" | tee >(curl -X POST -d @- http://your-log-server.com)
