name: CI Worker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate a multi-step build process
        run: |
          echo "Starting the build process..."
          echo "---------------------------------"
          
          echo "Step 1: Installing dependencies..."
          sleep 5
          echo "Dependencies installed."
          echo "---------------------------------"

          echo "Step 2: Running tests..."
          for i in {1..5}; do
            echo "Running test $i..."
            sleep 2
          done
          echo "All tests passed."
          echo "---------------------------------"

          echo "Step 3: Building the application..."
          sleep 5
          echo "Build complete."
          echo "---------------------------------"

          echo "Worker job is now complete."