name: CI Worker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debugging Info
        run: |
          echo "hello from the CI Worker"
          echo "This is where your build, test, and deploy steps would go."
          ls -al
          pwd
          echo "Worker job is now complete."